### ISSUE TITLE
Inconsistent use of ランク and ランキング

### ISSUE THREAD

**Issue by SamyNarrainen** [summersky1/anibook#48]
In the details for a specific title, 知名度ランキング and 評価ランキング both use ランキング while exclusively 総合ランク uses ランク.

**Comment by summersky1** [comment]
I did that on purpose since I want 総合ランク to refer to the letter and not the number. Not sure if it's necessarily correct Japanese though.

**Comment by summersky1** [comment]
Fixed with b34338a15466ba89a63d803e83e2ab7dcc090a16
