### ISSUE TITLE
View all option

### ISSUE THREAD

**Issue by SamyNarrainen** [summersky1/anibook#49]
In addition to the option to show more results, it would be desirable to have a similar view all option which would show all possible results at once. To achieve this at the moment is a painful repeat process of 'view more' then wait.

**Comment by summersky1** [comment]
So there is a reason I haven't added a show all option yet.
An individual API request is sent for each anime before displaying each search result and so a show all option require a really long wait time.

**Comment by summersky1** [comment]
Eventually I plan to save large amounts of anime data and search the database directly, at which point a show all option would be viable.

**Comment by SamyNarrainen** [comment]
> Eventually I plan to save large amounts of anime data and search the database directly, at which point a show all option would be viable.

Given that the data is sourced from MAL, are there any legal concerns with storing that data permanently? Not that I know personally, but it's a curious question for MAL's API terms and service I would imagine.

**Comment by summersky1** [comment]
> Given that the data is sourced from MAL, are there any legal concerns with storing that data permanently?

MAL removed their official API ages ago, I'm using an unofficial API.
https://github.com/jikan-me/jikan

I should update my Readme.

**Comment by summersky1** [comment]
Readme updated.
