### ISSUE TITLE
DATABASE NAME is not necessary to be secret

### ISSUE THREAD

**Issue by corselia** [summersky1/anibook#51]
Because to be secret is meaningless. It is like a sqlite3's filename.

- Remove
https://github.com/summersky1/anibook/blob/892199b904ad598b3871417523e012ff38fc9d6b/.env.sample#L4

- Write to `config/database.yml` directly

- Pros
  - Only in `.env`, all each user's configurations are completed if other conf environments are also included in `.env`

**Comment by summersky1** [comment]
I don't think it's that big of an issue because the developer can easily choose their own database name.

**Comment by corselia** [comment]
When each developer creates with each name as he/she likes, do you think how will the team development become?

**Comment by corselia** [comment]
If you develop and work by yourself eternally until you die, don't notice this.

**Comment by summersky1** [comment]
Right now I'm the only one that has access to the database so I think it is fine.

**Comment by corselia** [comment]
I see.
