### ISSUE TITLE
Add RSpec ASAP

### ISSUE THREAD

**Issue by corselia** [summersky1/anibook#52]
- RSpec is a de facto standard test framework on Rails
- When you `rails g`, a test file is added automatically and its file is based on selected framework
  - The default framework is `minitest` so you already created `minitest`'s test files but there are no rspec's files
- Related #6

**Comment by summersky1** [comment]
I think it's still early to write tests because the specification still isn't fixed.

**Comment by corselia** [comment]
Namely, you never write tests. Is it ok?

**Comment by summersky1** [comment]
I know that knowing how to write tests is important but I want to complete basic functionality first. I'm still learning a lot about how to develop using RoR and so my implementation tends to change as I learn more. Writing tests would slow down development quite a lot at this stage.

**Comment by corselia** [comment]
I see.
